// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwcoxwffcdfndzrdvtep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Y294d2ZmY2RmbmR6cmR2dGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODEwNjIsImV4cCI6MjA2NDQ1NzA2Mn0.bjR0ytiuJHPIeOjjuHCVsveReiGPxbFjDr0LzjY4HbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);